### ISSUE TITLE
Inquiry on Using ProteinGenerator for De Novo Design of Protein Binders

### ISSUE THREAD

**Issue by assiduous006** [RosettaCommons/protein_generator#16]
Hello,

I am writing to inquire about the capabilities of the ProteinGenerator tool, which I came across in your recent publication: "Joint Generation of Protein Sequence and Structure with RoseTTAFold Sequence Space Diffusion"​​.

My interest lies in exploring the potential of ProteinGenerator to design novel protein binders against specific target proteins. Given the tool's ability to generate protein sequences and structures simultaneously, I am keen to understand if it can be applied to the de novo design of binders, particularly in the context of therapeutic development or other biotechnological applications.

Could you provide information on whether ProteinGenerator is suitable for this purpose? Additionally, I would appreciate any guidance on how to best approach using the tool for designing protein binders, including any relevant parameters or considerations.

Thank you for your time and the impressive work on this innovative tool. I look forward to the possibility of utilizing ProteinGenerator in my research.

Best regards,

Eric

**Comment by 0merle0** [comment]
Hi there, happy to help! We actually do have an example of binder design here: `examples/binder_design.sh` Generally it works by providing a target structure and sequence, and labelling hotspots on the target to for the binder to target. Usually you just specify the binder length, unless you know something about it's structure or sequence. Happy to discuss this further for you if you have any other questions, feel free to email me jgershon@uw.edu

**Comment by assiduous006** [comment]
Hi,

Thank you for your prompt response and the helpful information. The example you provided on binder design seems to align perfectly with what I'm aiming to achieve. I'll review `examples/binder_design.sh` to better understand the process and how I might adapt it to my specific target proteins.

I may take you up on your offer to discuss further via email, especially once I've dived into the example script and if any nuanced questions arise.

Thanks once again for your assistance and the remarkable work on ProteinGenerator.

Best regards,

Eric

**Comment by HanLab-OSU** [comment]
hi, Where can I find examples/binder_design.sh? it is not in the examples. Could you please add some sample runs for design binders? Thanks, Renzhi
