### ISSUE TITLE
Description of example scripts

### ISSUE THREAD

**Issue by johnnytam100** [RosettaCommons/protein_generator#2]
Hi Protein Generator authors. Great work! I love the seq2seq property of this model.
Currently, I have a sequence that I want to diversify using this Protein Generator.
However, I don't know what positions should I put the masks (i.e. 'X').
May I know if Protein Generator can perform such a diversification task without specifying any masks?
Relatedly, it will be much more helpful if there are more descriptions of the example scripts, like in the RFDiffusion repo.

**Comment by 0merle0** [comment]
Hey, I will try and beef up the descriptions for each of the examples, if you are interested in diversifying a sequence you can input the sequence and run in partial diffusion mode by setting the sampling temp < 1.0, for example if T=50 and sampling_temp=0.2 the model will run 10 steps of diffusion noising the input sequence to 20% if the trajectory, does that make sense?

**Comment by johnnytam100** [comment]
In this case, I suppose masks still have to be self-defined? 
I tried the settings but the input sequence was kept unchanged.

**Comment by 0merle0** [comment]
ahh looking back through this it is actually my bad, an unintended bug occurred where masking wasn't set up properly if trying to diffuse from sequence input, I just pushed a quick fix in `utils/sampler.py` that should fix this and I also added an example in `examples/sequence_partial_diffusion.py` in the examples folder. I will add descriptions for all the examples too, I think its a nice idea.

**Comment by johnnytam100** [comment]
Thank you! It worked now!
Btw, I wonder if is there a relationship between `--T` and `--sampling_temp`?

**Comment by 0merle0** [comment]
There is! the sampling_temp argument will noise the starting sequence int(T*sampling_temp) steps toward fully noised T
