### ISSUE TITLE
Code for the Model In Action visualization

### ISSUE THREAD

**Issue by alexioana** [RosettaCommons/protein_generator#3]
Hello! 

Just wondering if the code you used to create the model in action video is available?

**Comment by 0merle0** [comment]
it is not but I can send you a notebook if you're interested in playing around with it, there is a save_all_steps argument which can be used to save all intermediate sequences and structures

**Comment by alexioana** [comment]
hey! yes please that would be amazing!

**Comment by jsrimr** [comment]
If you don't mind, can I also get the notebook which generates the video in readme?🙏

**Comment by 0merle0** [comment]
Hi, so sorry I completely forgot about this!

Let me know if there are any functions not working or parts that don't make
sense
 trajectory.ipynb.zip
<https://drive.google.com/file/d/1h8g-8zTVKPB6z2GL205PcBZumHQVsDtd/view?usp=drive_web>
