### ISSUE TITLE
Documentation for --contigs syntax

### ISSUE THREAD

**Issue by y1zhou** [RosettaCommons/protein_generator#4]
In the current `argparse` help document, `--contigs` takes "Pieces of input protein to keep", but details seem to be missing on the specific syntax. Multiple example bash scripts contain this argument, e.g. in `binder_design.sh` there's `B1-110,0 25-75`, in `motif_scaffolding.sh` there's `0-25,A163-181,25-30`, but none seem to provide comments on what these actually mean. Could you please provide some insight on:

- When should chain names be given and when can they be omitted?
- Should commas or spaces be used as separators for multiple contigs?
- What are the ranges for? What does zero mean?

Appreciate the help!

**Comment by y1zhou** [comment]
Can I assume the syntax is consistent with [RFDiffusion](https://github.com/RosettaCommons/RFdiffusion)? Main differences would just be:

- removed `[]` (probably due to this package not using hydra), and
- using `,` as separators instead of `/`, which would also explain the change from `/0 ` to `,0 ` for specifying separate chains.

**Comment by 0merle0** [comment]
Hi yes sorry we should have added some more documentation to assist here:

The basic setup and syntax is nearly identical to RFDiffusion, to grab residues (seq and str) on a pdb chain you will provide the chain letter followed by a range of residues as indexed in the pdb file for example (A3-10) is the syntax to select residues 3-10 on chain A (the chain always needs to be specified). To add diffused residues to either side of this motif you can specify a range or discrete value without a chain letter infront. To add 15 residues before the motif and 20-30 residues (randomly sampled) after use the following syntax: 15,A3-10,20-30   commas are used to separate regions selected from the pdb and designed (diffused) resiudes which will be added. A comma space (or comma 0) can be used to  specify a chain break for example if you want to generate a 25 to 75 residue binder to chain B, you can use the following syntax: B1-110,0 25-75     does this help make the syntax a little more readable?

**Comment by y1zhou** [comment]
Perfect! Thanks for the clarification.
