### ISSUE TITLE
The start_num argument for the primary inference pipeline does not work.  

### ISSUE THREAD

**Issue by anirudhbhashyam** [RosettaCommons/protein_generator#9]
# The Problem

The repository was cloned and the environment installed on a machine with the following configuration:
| Component | Config |
| ------------- | ------- |
| OS | Ubuntu 20.04.5 LTS |
| RAM | 200 GB | 
| GPU | NVIDIA | NVIDIA A100-SXM4-40GB |

While running the following scaffolding command (the PDB was downloaded before hand): 
```bash
python ./inference.py --pdb ./7x9e.pdb --out ./results/7x9e_scaffold --contigs 20-24,E813-825,20-24 --start_num 37 --num_designs 2
```
**the designs that are created do not start from 37 but from 0**.  As seen in stdout below:

![Screenshot (81)](https://github.com/RosettaCommons/protein_generator/assets/42548840/5ebbc2ca-44c6-438a-b52e-638067bb72ae)

# The Fix
This seems to be a problem in how the sampler class is initialised which calls `reset_design_num` instead of setting the `design_num` attribute from `args` (where `start_num` by default is 0). The pull request is [here](https://github.com/RosettaCommons/protein_generator/pull/8).

**Comment by 0merle0** [comment]
just merged your pull request, thanks!
